### ISSUE TITLE
JIRA 6.5: Saving Fields consistently throws a 400: Bad Request

### ISSUE THREAD

**Issue by intere** [sumoheavy/jira-ruby#105] opened 2015-05-08 15:30 UTC
I have debugged this and found that the base.rb - url method (when hitting the if ``@attrs['self']`` case) was not utilizing the ``prefix`` and creating urls that did not start with a slash (``/``) prefix.  I'm going to issue a pull request to address this.

I have tested it and found it to work for Jira 6.5.  I would assume this will be a universal fix, though.

**Comment by legkvla** [comment] 2015-06-07 17:08
Looks like #100 is duplicate of this issue.

**Comment by bobbrodie** [comment] 2016-06-29 16:29
#100 Has been merged and closed - let's reopen this if necessary. Thanks!

**Closed by bobbrodie** 2016-06-29 16:29 UTC
