### ISSUE TITLE
`project.issues` method does not return all issues in the project as promised

### ISSUE THREAD

**Issue by fabianlim1989** [sumoheavy/jira-ruby#173] opened 2016-08-26 23:57 UTC
```
project.issues.each do |issue|
  puts "#{issue.id} - #{issue.fields['summary']}"
end
```

It hits the limit of `maxResult` and only returns the first 50 issues of the project.

Addition looping is required to retrieve ALL issues.

**Comment by ondrejbartas** [comment] 2016-09-14 16:29
```
issues = []
begin
  issues << source_project.issues(startAt: issues.size * 50)
end while issues.last.any?
issues.flatten.sort_by(&:id)
```

**Comment by bobbrodie** [comment] 2016-11-13 01:39
Closing this as a duplicate of #143 which should cover Issue.all and all inherited aspects.

**Closed by bobbrodie** 2016-11-13 01:39 UTC
